### ISSUE TITLE
Create Named User

### ISSUE THREAD

**Issue by moelaj** [foxysoft/idm-connector-bobj#22]
I get the following error message when creating a new user through IDM:
_fx_bobj_createUser: com.crystaldecisions.sdk.occa.infostore.internal.InfoStoreException: You do not have any Concurrent User Licenses to make this user a concurrent user. You have 0 Concurrent User Licenses._

How do I force the connector to use Named Users instead.
Thanks

**Comment by boskamp** [comment]
In the "CreateUser" plugin process, open the first action task "Create BOBJ User". On the destination tab of the enclosed toGeneric pass, change the line with attribute name SI_NAMEDUSER and set the value to `{BOOLEAN}true`

![grafik](https://user-images.githubusercontent.com/4026819/184433609-0dc4e160-e1d5-4530-897f-9160964abb3f.png)
Let me know if it works.

**Comment by moelaj** [comment]
That worked perfectly.
Thanks
